### ISSUE TITLE
A gem install chef-provisioning-oneview fails due to libyajl2

### ISSUE THREAD

**Issue by thebsdbox** [HewlettPackard/chef-provisioning-oneview#43]
Error message is as follows:

```
gem install chef-provisioning-oneview
Building native extensions.  This could take a while...
ERROR:  Error installing chef-provisioning-oneview:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
creating Makefile
/usr/local/share/gems/gems/libyajl2-1.2.0/ext/libyajl2
extconf.rb:104:in `makemakefiles': unhanded exception
	from extconf.rb:138:in `<main>'
```

The fix is to ensure that both **make** and **gcc** packages are installed..

**Comment by jsmartt** [comment]
Thanks @thebsdbox ! I captured this in the [Troubleshooting Wiki Page](https://github.com/HewlettPackard/chef-provisioning-oneview/wiki/Troubleshooting) also. Closing
